### ISSUE TITLE
Calculate the maximum number of regions

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#45]
Hello,

I struggled a lot lately but today I took an amazing step forward. Take a look:
First the edges processed from the annotations look very clear and distinct:
![annotation_50um_edges](https://user-images.githubusercontent.com/67700096/121524817-f9346e00-c9f7-11eb-8cfd-d0b77e589e19.png)
Also the edges from my nissl-stack look somewhat fine:
![nissl_50um_edges](https://user-images.githubusercontent.com/67700096/121524926-1701d300-c9f8-11eb-925f-5765e69524e7.png)
And in the  end the refinement step apparently worked well:
![refined_annotation_50um_edges](https://user-images.githubusercontent.com/67700096/121525169-516b7000-c9f8-11eb-802b-bc1d242ab67f.png)

> root - INFO - foreground DSC: 0.5242654798749209
> root - INFO - 
> root - INFO - Measuring overlap of individual original and watershed labels:
> root - INFO - Mean label-by-label DSC: 0.8537643102287721
> root - INFO - 
> Measuring overlap of combined original and watershed labels:
> root - INFO - Mean label-by-label DSC: 1.0

I came so far just because of your magellan mapper. Thanks again!

Now I'm facing a new question:
**How many regions can/ should I keep in the atlas without lowering the accuracy of the registration?** 
I know your initial target was to hold on every region, but the 2D-atlases you used covered a lot higher amount of the 3D-atlas (about 75% for one hemisphere).

But my base is a lot smaller. That's why I lowered the resolution of the goal 3D-atlas so I don't have to interpolate to many slices. Right now I'm at (isotroph) 50um and have to interpolate 75% of the slices in the atlas (the 2D atlas had 62 plates, the 3D template now got 271 slices). 

There're 722 regions in the original 2D atlas, and a lot of them (majority) aren't defined by histological borders or at least some contrast changes. So it seems impossible to do a non-linear registration on "knowledge" based regions. 
i'm thinking about merging all regions that have no histological boundaries and / or have an area smaller than 9 pixels (i.e. a full outline and one pixel for the volume itself). What do you think?

**Comment by yoda-vid** [comment]
That looks fantastic, @SaibotMagd! The edges look great from both your annotation and Nissl images, and I'm really glad the refinement step worked nicely too.

Great question about the max regions to include. I agree that if many of the smaller regions don't have histological borders, it will be harder to interpolate them and also to assess their accuracy. I don't know of a specific number or size limit of regions, but your strategy of using merged super-structures makes sense, especially as a first step to follow the histological boundaries where they exist.

After interpolating the gross structures, it may be easier afterward to subdivide them based on the finer sub-regional boundaries since they will each be contained within a gross 3D structure. That way you can recover the smaller structures within the confinement of their parent structures.

Really awesome work!
