### ISSUE TITLE
Crash in first run

### ISSUE THREAD

**Issue by clifduhn** [sanderslab/magellanmapper#8]
MagellanMapper bounces a few times and immediately quits on MacOS 10.15.7. Crash happens on first run of application and app quits before any error is logged abd before user directory is created.
Restarting computer and re-launching app solves issue.

**Comment by yoda-vid** [comment]
Thanks for reporting @clifduhn ! I can reproduce this with the v1.4beta2 release (https://github.com/sanderslab/magellanmapper/releases/tag/v1.4-beta.2). Looks like the app is starting to load but never completes and then quits. The app starts without a hitch on the next and subsequent launches.

I can actually get this again each time I copy the `MagellanMapper.app` file from the downloaded `.dmg` to `/Applications` and rerun the app. The sequence for me is this, on the same macOS 10.15.7:
1. Right-click on the app in Applications in Finder, select open, get unidentified developer warning with only the option to Move to Trash or Cancel
2. Right-click and open the app again, getting the warning but with the option to open anyway, leading to a bouncing icon in the Dock followed by a crash without any app window display
3. Right-click and open the app yet again...open sesame!
4. After exit, then double-click to launch as normal

So it seems to be related to the first-launch security screening. The workaround for now is to launch repeatedly the first time, but we'll clearly need to hunt this down.

**Comment by yoda-vid** [comment]
Tracked this down to a spurious argument during first launch of .app bundles, which leads to a crash because the command-line parser doesn't recognize this argument. Apparently macOS passes an argument of the form, `--psn_xyz`, where `xyz` is a process serial number, to the app when it has an internet-download quarantine flag (see [comment](https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder#comment102377986_10242200)).

Normally PyInstaller filters out this argument (see https://github.com/pyinstaller/pyinstaller/issues/5442), but for some reason it slips through here. Perhaps launching the PyInstaller-built app with the quarantine flag somehow bypasses this filtering (eg see https://github.com/pyinstaller/pyinstaller/issues/5021#issuecomment-667657071 where the argument appears in another situation with PyInstaller).

As a workaround, I changed the command-line argument parser (`argparse`) to read only known arguments so that it filters out these `-psn_xyz` arguments. This change also has the advantage of tolerating any other unrecognized user argument that previously would have crashed the app, although the downside is that it's not as obvious when the user gave an argument that was ignored. To make this a littler clearer, any unrecognized arg will at least be reported to the user after parsing all args.

Fix will be included in the next installer build. Thanks again for reporting this, @clifduhn!
